spring.application.name=MyCampus

# MongoDB 配置
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/mycampus}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:mycampus}

# 开启索引，使得unique能够生效
spring.data.mongodb.auto-index-creation=true

# 应用程序端口配置
server.port=8080

# 日志配置
logging.level.com.mycampusdev.mycampus=DEBUG
logging.file.name=logs/mycampus.log

# 文件上传大小限制配置
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
