spring.application.name=MyCampus

# MongoDB 配置
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/mycampus}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:mycampus}

# 应用程序端口配置
server.port=8080

# 日志配置
logging.level.com.mycampusdev.mycampus=DEBUG
logging.file.name=logs/mycampus.log
